### ISSUE TITLE
When I switch to Containers pane. it give me " - privileged" error

### ISSUE THREAD

**Issue by liudonghua123** [lexandro/dockermon#2]
That's a nice chrome app, in `Images` pane, it works well, but when I switched to the `Containers` pane, it only shown me " - privileged" error on the bottom.

Here is some pieces of docker host infomation

```
Docker server version:1.7.0
Remote Api Version:1.19
Kernel Version:3.16.0-30-generic
Go Version:go1.4.2
Storage Driver:aufs
Execution Driver:native-0.2
```

**Comment by lexandro** [comment]
Hi,
Thanks for letting me know this. When I'm back from my holiday, I'll check it :) Probably on Sunday :) I haven't tested it on 1.7, maybe it needs some changes.

**Comment by lexandro** [comment]
Hi!

I tested on my own docker 1.7 instance and all worked fine, so I need your help. Please run the following commands and copy the results or attach screenshots:
1. docker run -d --name test lexandro/echo-repeat 
2. docker ps
3. Check it in dockery
4. optional: docker ps -a

Then you could remove the test: docker kill test && docker rm test. 

The lexandro/echo-repeat does nothing just shows the time in every second endlessly. I created for testing purposes :)

Thank you for your help!

Robert

**Comment by liudonghua123** [comment]
Here is the result and screenshot.

```
ldh@ldh-HVM-domU:~$ docker run -d --name test lexandro/echo-repeat
Unable to find image 'lexandro/echo-repeat:latest' locally
latest: Pulling from lexandro/echo-repeat
b9798d26430b: Pull complete 
53466618c569: Already exists 
53466618c569: Pulling fs layer 
428b411c28f0: Already exists 
435050075b3f: Already exists 
9fd3c8c9af32: Already exists 
Digest: sha256:103ca35210e342b03b66f4cecde4e79be734875ebda02747126f2f371c4f9087
Status: Downloaded newer image for lexandro/echo-repeat:latest
78255c248efd7ee14a5a460b9a87a40fdc5458cee59c3ba05712237dc14ddbc2
ldh@ldh-HVM-domU:~$ 
ldh@ldh-HVM-domU:~$ 
ldh@ldh-HVM-domU:~$ docker ps
CONTAINER ID        IMAGE                  COMMAND                CREATED             STATUS              PORTS               NAMES
78255c248efd        lexandro/echo-repeat   "/bin/sh -c '/bin/ba   8 seconds ago       Up 8 seconds                            test                
ldh@ldh-HVM-domU:~$
```

![](https://raw.githubusercontent.com/liudonghua123/some_pieces/master/pics/dockery_container_error_info.png)

**Comment by lexandro** [comment]
I think I see your problem. The "/!\ - privileged"  line is a hint. If you run your container in privileged mode this triangle added to the ID. Maybe this is not descriptive enough. Any ideas to improve? :)

![privileged_demo](https://cloud.githubusercontent.com/assets/146177/8396597/569a3df2-1dad-11e5-8718-3033224acf1d.png)

Does it solve your problem?

**Comment by liudonghua123** [comment]
Hi,
When I also run another container

```
ldh@ldh-HVM-domU:~$ docker run -itd ubuntu
63aca8da2654be0071329560f830750ca99e91897ef2173d5b8a8a01759d77f0
ldh@ldh-HVM-domU:~$ 
ldh@ldh-HVM-domU:~$ docker ps
CONTAINER ID        IMAGE                  COMMAND                CREATED             STATUS              PORTS               NAMES
63aca8da2654        ubuntu                 "/bin/bash"            7 seconds ago       Up 6 seconds                            mad_rosalind        
78255c248efd        lexandro/echo-repeat   "/bin/sh -c '/bin/ba   11 minutes ago      Up 11 minutes                           test                
ldh@ldh-HVM-domU:~$
```

And the correspond screenshot is as follows.
![](https://raw.githubusercontent.com/liudonghua123/some_pieces/master/pics/dockery_container_error_info2.png)

**Strange, I could not see any running containers here the day before yesterday.**

**Comment by lexandro** [comment]
this screen should show the similar result of docker ps.

If you want to see all your containers please click the "All" checkbox or try docker ps -a.

**Comment by liudonghua123** [comment]
OK, thank you very much!
