### ISSUE TITLE
dockery doesn't work in Firefox

### ISSUE THREAD

**Issue by jacekbilski** [lexandro/dockermon#3]
Hi Robert,
I was trying to use dockery with Firefox, but it doesn't work. With chromium it does. Firebug tells me:
"TypeError: setting a property that has only a getter @     app.modules.js (line 28, col 12)". That means line "$delegate.history = null;"
Do you plan to support Firefox?
Thanks
Jacek

**Comment by lexandro** [comment]
Hi there,

The fix is pushed, the next image build should run with FF again.

**Comment by jacekbilski** [comment]
Now it works, thanks.

**Comment by lexandro** [comment]
I made a small mistake in the code. Thanks for letting me know :)
