### ISSUE TITLE
dockery docker seems not work

### ISSUE THREAD

**Issue by liudonghua123** [lexandro/dockermon#5]
I followed the documentation, edited `/etc/default/docker` file, added the lines below and restart the docker deamon.

```
DOCKER_OPTS='-H tcp://0.0.0.0:2375 -api-enable-cors'
```

And then I run `docker run -d -p 40000:80 --name dockery lexandro/dockery`

On the browser I created a host, I saw some errors(`GET http://myhost:40000 (Not Found)`) on Chrome console. And it seemed couldn't get connected.

Any ideas? 

![screen shot 2015-08-06 at 19 44 28](https://cloud.githubusercontent.com/assets/2276718/9110855/c51c3142-3c73-11e5-80b8-3af30c6a56ce.png)

**Comment by lexandro** [comment]
The reason because you configured the docker daemon to listen on port 2375.

The port 40.000 is assigned the dockery application's container.

So the http://<server>:40000 opens docker and the http://<server>:2375 is the link you should add within the applicaton.

Robert

**Comment by liudonghua123** [comment]
Thanks, it works! I recommend adding this small note to improve the documentation.

**Comment by lexandro** [comment]
Not a bad idea. I'll update it at weekend.

At the moment I'm dying because of the heat here :)
