### ISSUE TITLE
some host are always disconnected

### ISSUE THREAD

**Issue by yanglei** [lexandro/dockermon#6]
I configured my three physical machines like this:
DOCKER_OPTS="-H tcp://0.0.0.0:49173 -H unix:///var/run/docker.sock -api-enable-cors"
in page "hosts", I found one machine is connected. however the other two machines always are disconnected.
I guess maybe some port configuration issue in firewall.
Could you help point out what port will be used to discover hosts in dockery?

**Comment by lexandro** [comment]
I need some extra infos: 
- what is your docker version? 
- are you running dockery as docker image/chrome app or hosted from http://docker.io/dockery ?
- in NON CHROME case please press F12 (chrome) or check the development console to see the error message of the app and copy here. In chrome app mode you can go settings/extension/ page and on the Dockery app click on "inspect views index.html" to see the debug output.

I hope we could see some meaningful error messages :)

**Comment by yanglei** [comment]
a) the docker version 1.7.1, build 786b29d
b) I run the dockery as chrome app. which downloaded from chrome app store. docker version 0.2.9
c) the debug output: 
=================
chrome storage
services.js:205 {"hosts":"[{\"id\":\"dtegc9ag5\",\"name\":\"slave32\",\"url\":\"http://cti-shz1-asvl-slave32.sh.intel.com:49173\",\"created\":\"2015-08-31T04:41:42.805Z\",\"lastConnected\":\"2015-08-31T05:37:43.067Z\",\"status\":true,\"defaultConnection\":false,\"selected\":false,\"pinging\":false,\"editHostName\":\"slave32\",\"editHostUrl\":\"http://cti-shz1-asvl-slave32.sh.intel.com:49173\",\"editHostEnabled\":true},{\"id\":\"qjv5scwd2\",\"name\":\"slave08\",\"url\":\"http://cti-shz1-asvl-slave08.sh.intel.com:49173\",\"created\":\"2015-08-31T05:58:10.417Z\",\"lastConnected\":null,\"status\":false,\"defaultConnection\":false,\"selected\":false,\"pinging\":true,\"editHostName\":\"slave08\",\"editHostUrl\":\"http://cti-shz1-asvl-slave08.sh.intel.com:49173\",\"editHostEnabled\":false},{\"id\":\"8zvrem75y\",\"name\":\"slave02\",\"url\":\"http://cti-shz1-asvl-slave02.sh.intel.com:49173\",\"created\":\"2015-08-31T06:40:34.244Z\",\"lastConnected\":null,\"status\":false,\"defaultConnection\":false,\"selected\":false,\"editHostEnabled\":false,\"pinging\":true,\"editHostName\":\"slave02\",\"editHostUrl\":\"http://cti-shz1-asvl-slave02.sh.intel.com:49173\"}]"}
http://cti-shz1-asvl-slave08.sh.intel.com:49173/_ping Failed to load resource: net::ERR_CONNECTION_TIMED_OUT
http://cti-shz1-asvl-slave02.sh.intel.com:49173/_ping Failed to load resource: net::ERR_CONNECTION_TIMED_OUT
angular.js:10506 GET http://cti-shz1-asvl-slave02.sh.intel.com:49173/_ping net::ERR_CONNECTION_TIMED_OUT(anonymous function) @ angular.js:10506sendReq @ angular.js:10325serverRequest @ angular.js:10037processQueue @ angular.js:14551(anonymous function) @ angular.js:14567Scope.$eval @ angular.js:15830Scope.$digest @ angular.js:15641Scope.$apply @ angular.js:15935(anonymous function) @ angular.js:17691completeOutstandingRequest @ angular.js:5387(anonymous function) @ angular.js:5659
angular.js:10506 GET http://cti-shz1-asvl-slave08.sh.intel.com:49173/_ping net::ERR_CONNECTION_TIMED_OUT(anonymous function) @ angular.js:10506sendReq @ angular.js:10325serverRequest @ angular.js:10037processQueue @ angular.js:14551(anonymous function) @ angular.js:14567Scope.$eval @ angular.js:15830Scope.$digest @ angular.js:15641Scope.$apply @ angular.js:15935(anonymous function) @ angular.js:17691completeOutstandingRequest @ angular.js:5387(anonymous function) @ angular.js:5659
angular.js:10506 GET http://cti-shz1-asvl-slave08.sh.intel.com:49173/_ping net::ERR_CONNECTION_TIMED_OUT(anonymous function) @ angular.js:10506sendReq @ angular.js:10325serverRequest @ angular.js:10037processQueue @ angular.js:14551(anonymous function) @ angular.js:14567Scope.$eval @ angular.js:15830Scope.$digest @ angular.js:15641Scope.$apply @ angular.js:15935(anonymous function) @ angular.js:17691completeOutstandingRequest @ angular.js:5387(anonymous function) @ angular.js:5659
angular.js:10506 GET http://cti-shz1-asvl-slave02.sh.intel.com:49173/_ping net::ERR_CONNECTION_TIMED_OUT(anonymous function) @ angular.js:10506sendReq @ angular.js:10325serverRequest @ angular.js:10037processQueue @ angular.js:14551(anonymous function) @ angular.js:14567Scope.$eval @ angular.js:15830Scope.$digest @ angular.js:15641Scope.$apply @ angular.js:15935(anonymous function) @ angular.js:17691completeOutstandingRequest @ angular.js:5387(anonymous function) @ angular.js:5659
angular.js:10506 GET http://cti-shz1-asvl-slave08.sh.intel.com:49173/_ping net::ERR_CONNECTION_TIMED_OUT(anonymous function) @ angular.js:10506sendReq @ angular.js:10325serverRequest @ angular.js:10037processQueue @ angular.js:14551(anonymous function) @ angular.js:14567Scope.$eval @ angular.js:15830Scope.$digest @ angular.js:15641Scope.$apply @ angular.js:15935(anonymous function) @ angular.js:17691completeOutstandingRequest @ angular.js:5387(anonymous function) @ angular.js:5659
angular.js:10506 GET http://cti-shz1-asvl-slave02.sh.intel.com:49173/_ping net::ERR_CONNECTION_TIMED_OUT(anonymous function) @ angular.js:10506sendReq @ angular.js:10325serverRequest @ angular.js:10037processQueue @ angular.js:14551(anonymous function) @ angular.js:14567Scope.$eval @ angular.js:15830Scope.$digest @ angular.js:15641Scope.$apply @ angular.js:15935(anonymous function) @ angular.js:17691completeOutstandingRequest @ angular.js:5387(anonymous function) @ angular.js:5659
angular.js:10506 GET http://cti-shz1-asvl-slave08.sh.intel.com:49173/_ping net::ERR_CONNECTION_TIMED_OUT(anonymous function) @ angular.js:10506sendReq @ angular.js:10325serverRequest @ angular.js:10037processQueue @ angular.js:14551(anonymous function) @ angular.js:14567Scope.$eval @ angular.js:15830Scope.$digest @ angular.js:15641Scope.$apply @ angular.js:15935(anonymous function) @ angular.js:17691completeOutstandingRequest @ angular.js:5387(anonymous function) @ angular.js:5659
angular.js:10506 GET http://cti-shz1-asvl-slave02.sh.intel.com:49173/_ping net::ERR_CONNECTION_TIMED_OUT(anonymous function) @ angular.js:10506sendReq @ angular.js:10325serverRequest @ angular.js:10037processQueue @ angular.js:14551(anonymous function) @ angular.js:14567Scope.$eval @ angular.js:15830Scope.$digest @ angular.js:15641Scope.$apply @ angular.js:15935(anonymous function) @ angular.js:17691completeOutstandingRequest @ angular.js:5387(anonymous function) @ angular.js:5659
angular.js:10506 GET http://cti-shz1-asvl-slave08.sh.intel.com:49173/_ping net::ERR_CONNECTION_TIMED_OUT(anonymous function) @ angular.js:10506sendReq @ angular.js:10325serverRequest @ angular.js:10037processQueue @ angular.js:14551(anonymous function) @ angular.js:14567Scope.$eval @ angular.js:15830Scope.$digest @ angular.js:15641Scope.$apply @ angular.js:15935(anonymous function) @ angular.js:17691completeOutstandingRequest @ angular.js:5387(anonymous function) @ angular.js:5659
angular.js:10506 GET http://cti-shz1-asvl-slave02.sh.intel.com:49173/_ping net::ERR_CONNECTION_TIMED_OUT

**Comment by yanglei** [comment]
one more comments, the docker version is same on the machine which dockery can connect to.

**Comment by yanglei** [comment]
Hi, Robert, 
I confirmed it is port configuration problem. When the port is allowed to access in firewall, the machine can be connected.
Please close the bug because it is not docker bug at all!
Thanks for your reply.

**Comment by lexandro** [comment]
Thanks for the feedback, I'm gonna close to it. In case of any issues, don't hesitate to open a new issue :)
